---
- name: "Configure {{ profile_name }} Server Profile"
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq '{{ profile_name }}'"
    api_body: {
      "Name": "{{ profile_name }}",
      "AssignedServer": {
        "Moid": "{{ server_moid }}"
      }
    }
  register: profile_resp
  when: server_moid is defined
  tags: server_profiles
# Deploy (or perform other profile_action) when tag is set
- name: Deploy (or user defined profile_action) Server Profile
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq '{{ profile_name }}'"
    api_body: {
      "Action": "{{ profile_action | default('Deploy') }}"
    }
  tags: [never, deploy]
