---
- name: "Configure {{ policy_name }} LAN Connectivity Policy"
  # Role will register a policy_resp
  import_role:
    name: policies/server_policies
  vars:
    resource_path: /vnic/LanConnectivityPolicies
    api_body: {
      "Name": "{{ policy_name }}"
    }
- name: "Configure {{ ethernet_qos }} Ethernet QoS Policy"
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthQosPolicies
    query_params:
      $filter: "Name eq '{{ ethernet_qos }}'"
    api_body: {
      "Name": "{{ ethernet_qos }}",
      "Mtu": "{{ mtu }}"
    }
  register: eth_qos_resp
- name: "Configure {{ ethernet_network }} Ethernet Network Policy"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthNetworkPolicies
    query_params:
      $filter: "Name eq '{{ ethernet_network }}'"
    api_body: {
      "Name": "{{ ethernet_network }}",
      "VlanSettings": {
        "Mode": "{{ vlan_mode }}",
        "DefaultVlan": "{{ default_vlan }}"
      }
    }
  register: eth_network_resp
- name: "Configure {{ ethernet_adapter }} Ethernet Adapter Policy"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthAdapterPolicies
    query_params:
      $filter: "Name eq '{{ ethernet_adapter }}'"
    api_body: {
      "Name": "{{ ethernet_adapter }}"
    }
  register: eth_adapter_resp
# vNIC configuration
- name: "Configure vNIC"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthIfs
    query_params:
      $filter: "LanConnectivityPolicy.Moid eq '{{ policy_resp.api_response.Moid }}' and Name eq '{{ item.name }}'"
    # Note that order and uplink are hardcoded below to the loop index (e.g., order/uplink 0 for 1st list element, 1 for next, etc.)
    api_body: {
      "Name": "{{ item.name }}",
      "Order": "{{ index }}",
      "Placement": {
        "Id": "{{ item.slot_id }}",
        "Uplink": "{{ index }}"
      },
      "EthAdapterPolicy": {
        "Moid": "{{ eth_adapter_resp.api_response.Moid }}"
      },
      "EthNetworkPolicy": {
        "Moid": "{{ eth_network_resp.api_response.Moid }}"
      },
      "EthQosPolicy": {
        "Moid": "{{ eth_qos_resp.api_response.Moid }}"
      },
      "LanConnectivityPolicy": {
        "Moid": "{{ policy_resp.api_response.Moid }}"
      }
    }
  loop: "{{ vnic_list }}"
  loop_control:
    index_var: index
