---
# host specific tasks to configure multiple targets
- hosts: "{{ target }}"
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
    target: intersight-devnet
  tasks:
  - name: Set hostname
    set_fact:
      hostname: "{{ inventory_hostname }}"
    when: hostname is not defined
  # find desired servers by SN (name in the API)
  - name: Lookup server
    intersight_rest_api:
      <<: *api_info
      resource_path: /compute/PhysicalSummaries
      query_params:
        $filter: "Name eq '{{ hostname }}'"
    register: server
  - debug:
      msg: "Server moid {{ server.api_response.Moid }}"
    when: server.api_response.Moid is defined
  - name: Assign server
    intersight_rest_api:
      <<: *api_info
      resource_path: /server/Profiles
      query_params:
        $filter: "Name eq '{{ server_profile }}'"
      api_body: {
          "AssignedServer": "{{ server.api_response.Moid }}"
      }
      state: "{{ resource_state }}"
    when: server.api_response.Moid is defined
  - name: Deploy server
    intersight_rest_api:
      <<: *api_info
      resource_path: /server/Profiles
      query_params:
        $filter: "Name eq '{{ server_profile }}'"
      api_body: {
          "Action": "Deploy"
      }
      state: "{{ resource_state }}"
