---
# host specific policies.  Use the ucs hosts group to configure multiple targets
- hosts: "{{ target }}"
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
    object_state: present
    target: ucs
  tasks:
  # Check HX Cluster profile state
  - name: Check HX Cluster Profile config state
    intersight_objects:
      <<: *api_info
      objects:
      - {
        "api_module": "intersight.apis.hyperflex_cluster_profile_api",
        "api_class": "HyperflexClusterProfileApi",
        "api_method_prefix": "hyperflex_cluster_profiles",
        "get_filter": "Name eq '{{ hx_profile_name }}'",
        "data_module": "intersight.models.hyperflex_cluster_profile",
        "data_class": "HyperflexClusterProfile"
      }
      state: "{{ object_state }}"
    register: initial_config
  # HX Cluster profile deploy
  - name: Deploy HX Cluster Profile
    intersight_objects:
      <<: *api_info
      objects:
      - {
        "api_module": "intersight.apis.hyperflex_cluster_profile_api",
        "api_class": "HyperflexClusterProfileApi",
        "api_method_prefix": "hyperflex_cluster_profiles",
        "object_moid": "{{ initial_config.api_response.moid }}",
        "data_module": "intersight.models.hyperflex_cluster_profile",
        "data_class": "HyperflexClusterProfile",
        "api_body": {
            "Action":"Deploy"
        }
      }
      state: "{{ object_state }}"
    when:
    - initial_config.api_response is defined
    - initial_config.api_response.config_context.config_state != 'Associated'
  # Wait for HX Cluster profile deploy
  - name: Wait for HX Cluster Profile deploy
    intersight_objects:
      <<: *api_info
      objects:
      - {
        "api_module": "intersight.apis.hyperflex_cluster_profile_api",
        "api_class": "HyperflexClusterProfileApi",
        "api_method_prefix": "hyperflex_cluster_profiles",
        "object_moid": "{{ initial_config.api_response.moid }}",
        "data_module": "intersight.models.hyperflex_cluster_profile",
        "data_class": "HyperflexClusterProfile"
      }
      state: "{{ object_state }}"
    when:
    - initial_config.api_response is defined
    - initial_config.api_response.config_context.config_state != 'Associated'
    register: result
    until: result.api_response.config_context.config_state == 'Associated'
    retries: 60
    delay: 120
