---
# retrieve facts from Intersight servers
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key | default('~/Downloads/SSOSecretKey.txt') }}"
      api_key_id: "{{ api_key_id | default('596cc79e5d91b400010d15ad/596cc7945d91b400010d154e/5b6275df3437357030a7795f') }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
  tasks:
    # find all servers
    - intersight_facts:
        <<: *api_info
        server_names:
      register: all_results
    # put standalone servers (IMC) into a file
    - lineinfile:
        path: "{{ playbook_dir }}/standalone_server_inventory"
        line: "{{ item.Name }} server_moid={{ item.Moid }} model={{ item.Model }} boot_policy={{ (item.Tags | items2dict(key_name='Key', value_name='Value'))['boot_policy'] | default('na') }}"
        create: true
      # ansible and jmespath contains have type differences, so to/from_json used
      loop: "{{ all_results.intersight_servers | json_query(platform_query) | to_json | from_json | json_query(model_query) }}"
      loop_control:
        label: "{{ item.Name }}"
      vars:
        # filter for IMC and C-Series only (no HX)
        platform_query: "[?PlatformType=='IMC']"
        model_query: "[?contains(Model, 'UCSC-C')]"
      when: all_results.intersight_servers is defined
