---
#
# HyperFlex Cluster Profile Actions (assign, deploy)
#
# The hosts group used is provided by the group variable or defaulted to 'DevNet_HX'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
- hosts: "{{ group | default('DevNet_HX') }}"
  connection: local
  gather_facts: false
  vars:
  # If your inventory or host/group_vars don't specify required api key information, you can set directly below:
  # api_private_key: ~/Downloads/SecretKey.txt
  # api_key_id: 5a3404ac3768393836093cab/5b02fa7e6d6c356772394170/5b02fad36d6c356772394449
  tasks:
    # Actions can be performed on multiple clusters at once
    # Assign Cluster Profile
    - import_role:
        name: service_profiles/hyperflex_cluster_profiles/actions
      vars:
        hx_profile_name: "{{ inventory_hostname }}"
        # options: Validate, Deploy, Abort
        # Can override on the command line: ansible-playbook ... -e hx_action=Deploy
        hx_action: Validate
      delegate_to: localhost
