---
# host specific policies.  Use the servers hosts group to configure multiple targets
- hosts: "{{ target }}"
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
    target: servers
    resource_state: present
  tasks:
  - name: Set hostname
    set_fact:
      hostname: "{{ inventory_hostname }}"
    when: hostname is not defined
  # find desired servers by SN (name in the API)
  - name: Lookup server
    intersight_rest_api:
      <<: *api_info
      resource_path: /compute/PhysicalSummaries
      query_params:
        $filter: "Name eq '{{ hostname }}'"
    register: server
  - debug:
      msg: "Server moid {{ server.api_response.Moid }}"
    when: server.api_response.Moid is defined
  - name: Update server firmware
    intersight_rest_api:
      <<: *api_info
      resource_path: /firmware/Upgrades
      # query by server returned above
      query_params:
        $filter: "Server.Moid eq '{{ server.api_response.Moid }}'"
      # nw_upgrade_full supported in UI, nw_upgrade_mount_only has partial API support
      api_body: {
          "NetworkShare": {
              "MapType": "nfs",
              "Upgradeoption": "nw_upgrade_full",
              "NfsServer": {
                  "RemoteIp": "172.22.250.88",
                  "RemoteShare": "/mnt/SHARE/ISOS/HUU/4.0",
                  "RemoteFile": "ucs-c220m5-huu-4.0.1a.iso"
              }
          },
          "UpgradeType": "network_upgrade",
          "Server": {
              "Moid": "{{ server.api_response.Moid }}"
          }
      }
      state: "{{ resource_state }}"
    when: server.api_response.Moid is defined
