---
# shared policies, use localhost so these tasks only run once
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "/Users/anganapa/Downloads/SecretKey-2.txt"
      api_key_id: "5a3404ac3768393836093cab/5b9c01db663471746d8faa10/5bacfd44366b683064f747c7"
    boot_policy_name: vmedia-hdd
    resource_state: present
  tasks:
  - name: Configure Boot Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /boot/PrecisionPolicies
      query_params:
        $filter: "Name eq '{{ boot_policy_name }}'"
      api_body: {
          "Name": "{{ boot_policy_name }}",
          "BootDevices": [
              {
                  "ObjectType": "boot.VirtualMedia",
                  "Enabled": true,
                  "Name": "remote-vmedia",
                  "Subtype": "cimc-mapped-dvd"
              },
              {
                  "ObjectType": "boot.LocalDisk",
                  "Enabled": true,
                  "Name": "boot-lun",
                  "Bootloader": null,
                  "Slot": "MRAID"
              }
          ],
          "ConfiguredBootMode": "Legacy",
          "EnforceUefiSecureBoot": false
      }
      state: "{{ resource_state }}"


---
# shared policies, use localhost so these tasks only run once
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "/Users/anganapa/Downloads/SecretKey-2.txt"
      api_key_id: "5a3404ac3768393836093cab/5b9c01db663471746d8faa10/5bacfd44366b683064f747c7"
    boot_policy_name: vmedia-policy
    resource_state: present
  tasks:
  - name: vmedia-policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /vmedia/Policy
      query_params:
        $filter: "Name eq '{{ boot_policy_name }}'"
      api_body: {
          "Name": "{{ boot_policy_name }}",
          "Tags": [],
          "DomainGroupMoid": "5b2541927a7662743465d027",
          "ConfiguredBootMode": "Legacy",
          "EnforceUefiSecureBoot": false
      }
      state: "{{ resource_state }}"



---
# shared policies, use localhost so these tasks only run once
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "/Users/anganapa/Downloads/SecretKey-2.txt"
      api_key_id: "5a3404ac3768393836093cab/5b9c01db663471746d8faa10/5bacfd44366b683064f747c7"
    boot_policy_name: bios-policy
    resource_state: present
  tasks:
  - name: bios-policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /bios/Policy
      query_params:
        $filter: "Name eq '{{ boot_policy_name }}'"
      api_body: {
          "Name": "{{ boot_policy_name }}",
          "Tags": [],
          "Moid": "5bad00fe7462713678e32764",
          "CdnEnable": "platform-default",
          "CdnSupport": "enabled",
          "ConfiguredBootMode": "Legacy",
          "EnforceUefiSecureBoot": false
      }
      state: "{{ resource_state }}"







    
