---
#
# Configure Server Profiles and Policies
#
# The hosts group used is provided by the group variable or defaulted to 'DevNet-Standalone'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME-Demo
#
- hosts: "{{ group | default('DevNet-Standalone') }}"
  connection: local
  gather_facts: false
  tasks:
    #
    # Configure profiles specific to server (run for each server in the inventory)
    # Server Profiles role will register a profile_resp and profile_resp list (from all hosts) can be used by policy tasks
    # The role supports Deploy or other user defined profile_action to be used with --tags deploy.  Do not add tags here for the import
    #
    - import_role:
        name: service_profiles/server_profiles
      vars:
        profile_name: "SP-{{ inventory_hostname }}"
      # Use the localhost's environment and Python
      delegate_to: localhost
    #
    # Enclose policy tasks in a block that runs once
    #
    - block:
        # Boot Order policy config
        - import_role:
            name: policies/server_policies/boot_order
          vars:
            boot_policy: vmedia-local-disk
            # optionally set a disk_slot for boot_order policy (e.g., MRAID, HBA, or slot number)
            # disk_slot: HBA      # Use the localhost's environment and Python
          tags: boot_order
        # Virtual Media policy config
        - import_role:
            name: policies/server_policies/virtual_media
          vars:
            vmedia_policy: nfs-cdd
            remote_file: VMware_ESXi_6.7.0_10302608_Custom_Cisco_6.7.1.1.iso
            remote_path: /mnt/SHARE/ISOS/ESX
            remote_hostname: 172.28.224.77
          tags: virtual_media
        # Bios policy config
        - import_role:
            name: policies/server_policies/bios
          vars:
            bios_policy: adaptive-memory
          tags: bios
      # Policies are common, so only run this block once and not for every host
      run_once: true
      delegate_to: localhost
