---
#
# Configure Server Policies and Profiles
#
# The hosts group used is provided by the group variable or defaulted to 'DevNet-Standalone'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME-Demo
#
- hosts: "{{ group | default('DevNet-Standalone') }}"
  connection: local
  gather_facts: false
  vars:
    # If your inventory or host/group_vars don't specify required api key information, you can set directly below:
    # api_private_key: ~/Downloads/SecretKey.txt
    # api_key_id: 5a3404ac3768393836093cab/5b02fa7e6d6c356772394170/5b02fad36d6c356772394449
    #
    # Virtual Media variables
    #
    vmedia_policy: nfs-esx-6-7U1
    bios_policy: adaptive-memory
  tasks:
    # Enclose tasks that only should run once in a block
    - block:
        # Enclose multiple boot order tasks in a block with a boot_order tag
        - block:
            - import_role:
                name: policies/server_policies/boot_order
              vars:
                boot_policy: vmedia-local-mraid
                disk_slot: MRAID
            - import_role:
                name: policies/server_policies/boot_order
              vars:
                boot_policy: vmedia-local-hba
                disk_slot: HBA
          tags: boot_order
        # Virtual Media policy config
        - import_role:
            name: policies/server_policies/virtual_media
          vars:
            remote_file: VMware_ESXi_6.7.0_10302608_Custom_Cisco_6.7.1.1.iso
            remote_path: /mnt/SHARE/ISOS/ESX
            remote_hostname: 172.28.224.77
          tags: virtual_media
        # Bios policy config
        - import_role:
            name: policies/server_policies/bios
          tags: bios
      # Use the localhost's environment and Python and only run once
      delegate_to: localhost
      run_once: true
    #
    # Configure profiles specific to server (run for each server in the inventory)
    #
    - import_role:
        name: service_profiles/server_profiles
      vars:
        profile_name: "SP-{{ inventory_hostname }}"
      # Use the localhost's environment and Python
      delegate_to: localhost
