---
# shared policies, use localhost so these tasks only run once
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
  tasks:
  - name: Configure BIOS Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /bios/Policies
      query_params:
        $filter: "Name eq '{{ bios_policy }}'"
      api_body: {
          "Name": "{{ bios_policy }}",
          "CdnEnable": "enabled",
          "CdnSupport": "enabled"
      }
      state: "{{ resource_state }}"
  - name: Configure Boot Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /boot/PrecisionPolicies
      query_params:
        $filter: "Name eq '{{ boot_policy }}'"
      api_body: {
          "Name": "{{ boot_policy }}",
          "BootDevices": [
              {
                  "ObjectType": "boot.VirtualMedia",
                  "Enabled": true,
                  "Name": "remote-vmedia",
                  "Subtype": "cimc-mapped-dvd"
              },
              {
                  "ObjectType": "boot.LocalDisk",
                  "Enabled": true,
                  "Name": "boot-lun",
                  "Bootloader": null,
                  "Slot": "MRAID"
              }
          ],
          "ConfiguredBootMode": "Legacy",
          "EnforceUefiSecureBoot": false
      }
      state: "{{ resource_state }}"

# host specific policies.  Use the servers hosts group to configure multiple targets
- hosts: "{{ target }}"
  connection: local
  gather_facts: no
  vars:
    target: servers
  tasks:
  - name: Set hostname
    set_fact:
      hostname: "{{ inventory_hostname }}"
    when: hostname is not defined
  - name: Configure vMedia Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /vmedia/Policies
      query_params:
        $filter: "Name eq '{{ vmedia_policy }}'"
      api_body: {
          "Name": "{{ vmedia_policy }}",
          "Mappings": [
              {
                  "MountProtocol": "nfs",
                  "VolumeName": "esx-ip",
                  "DeviceType": "cdd",
                  "HostName": "172.22.250.88",
                  "RemotePath": "/mnt/SHARE/ISOS/ESX",
                  "RemoteFile": "{{ remote_file }}"
              }
          ]
      }
      state: "{{ resource_state }}"

