---
- name: "Configure {{ hx_node_config_policy }} Node IP and Hostname Policy"
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /hyperflex/NodeConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_node_config_policy }}'"
    api_body: {
      "Name":"{{ hx_node_config_policy }}",
      "NodeNamePrefix":"{{ hx_profile_name }}",
      "MgmtIpRange":{
        "StartAddr":"{{ hx_mgmt_ip_start }}",
        "EndAddr":"{{ hx_mgmt_ip_end }}",
        "Netmask":"{{ hx_mgmt_netmask }}",
        "Gateway":"{{ hx_mgmt_gateway }}"
      },
      "HxdpIpRange":{
        "StartAddr":"{{ hx_dp_ip_start }}",
        "EndAddr":"{{ hx_dp_ip_end }}",
        "Netmask":"{{ hx_mgmt_netmask }}",
        "Gateway":"{{ hx_mgmt_gateway }}"
      }
    }
  register: node_config
