---
- name: "Configure {{ vmedia_policy }} Virtual Media Policy"
  intersight_rest_api:
    api_private_key: "{{ api_private_key }}"
    api_key_id: "{{ api_key_id }}"
    api_key_uri: "{{ api_key_uri }}"
    validate_certs: "{{ validate_certs }}"
    state: "{{ state }}"
    resource_path: /vmedia/Policies
    query_params:
      $filter: "Name eq '{{ vmedia_policy }}'"
    api_body: {
      "Name": "{{ vmedia_policy }}",
      "Mappings": [
        {
          "MountProtocol": "nfs",
          "VolumeName": "nfs-cdd",
          "DeviceType": "cdd",
          "HostName": "172.22.250.88",
          "RemotePath": "/mnt/SHARE/ISOS/ESX",
          "RemoteFile": "{{ remote_file }}"
        }
      ]
    }
