---
- name: "Configure {{ hx_cluster_network_policy }} Network Configuration Policy"
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /hyperflex/ClusterNetworkPolicies
    query_params:
      $filter: "Name eq '{{ hx_cluster_network_policy }}'"
    api_body: {
      "Name":"{{ hx_cluster_network_policy }}",
      "JumboFrame":false,
      "MgmtVlan":{
        "Name":"{{ hx_mgmt_vlan_name }}",
        "VlanId":"{{ hx_mgmt_vlan }}"
      },
      "VmMigrationVlan":{
        "Name":"{{ hx_migration_vlan_name }}",
        "VlanId":"{{ hx_migration_vlan }}"
      },
      "VmNetworkVlans":[
        {
          "Name":"{{ hx_vm_vlan_name }}",
          "ObjectType": "hyperflex.NamedVlan",
          "VlanId":"{{ hx_vm_vlan }}"
        }
      ],
      "UplinkSpeed": "1G"
    }
  register: cluster_network
