---
- name: "Configure {{ hx_vcenter_config_policy }} vCenter Policy"
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /hyperflex/VcenterConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_vcenter_config_policy }}'"
    api_body: {
      "Name":"{{ hx_vcenter_config_policy }}",
      "Hostname":"{{ hx_vcenter_hostname }}",
      "Username":"{{ hx_vcenter_username }}",
      "Password":"{{ hx_vcenter_password | default(omit) }}",
      "DataCenter":"{{ hx_vcenter_datacenter }}"
    }
  register: vcenter
